7-POST-comments complete. Returns body of comment and inserts into co…
Carl-with-a-C/be-nc-news pull request #7
Opened 2022-11-17 11:47 UTC by Carl-with-a-C

…mments database. tested for valid but unfound article, nonexistent username and invalid input criteria

2022-11-17 13:03 UTC, Harrison365 requested changes
Hey Carl :) 

Loving the big boy Barry comment 😆 
It looks like you are only returning the comment body in your model. We would like you to return and test for the entire comment object (votes etc.) 

I'm also a little worried about your 23503 error message being too specific ("User does not exist!") as there may be other endpoints that we add in the future where there is a foreign key during an insert that has nothing to do with usernames. Hope this makes sense 😬. Instead, you may want to make a custom error in the model by making another db.query to check for usernames. 

If you'd like me to expand on this let me know 😃  Otherwise, give us a shout when yuo're ready for us to look again 👍

2022-11-17 14:40 UTC, Harrison365 requested changes
Nice one :)
Please test for specific article_id rather than any(Number).
Also you could add one more test for a req.body with a username but no body. 
Cheers.

2022-11-17 14:42 UTC, Carl-with-a-C commented
Hi Harrison my 404 error test tests for valid article Id

2022-11-18 11:18 UTC, hevdevs approved these changes

2022-11-18 11:24 UTC, merged